USE [master]
GO
/****** Object:  Database [Apolices]    Script Date: 02/08/2020 23:37:57 ******/
CREATE DATABASE [Apolices]
GO
ALTER DATABASE [Apolices] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Apolices].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Apolices] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Apolices] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Apolices] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Apolices] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Apolices] SET ARITHABORT OFF 
GO
ALTER DATABASE [Apolices] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Apolices] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Apolices] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Apolices] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Apolices] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Apolices] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Apolices] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Apolices] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Apolices] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Apolices] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Apolices] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Apolices] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Apolices] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Apolices] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Apolices] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Apolices] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [Apolices] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Apolices] SET RECOVERY FULL 
GO
ALTER DATABASE [Apolices] SET  MULTI_USER 
GO
ALTER DATABASE [Apolices] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Apolices] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Apolices] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Apolices] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Apolices] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'Apolices', N'ON'
GO
ALTER DATABASE [Apolices] SET QUERY_STORE = OFF
GO
USE [Apolices]
GO
ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [Apolices]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 02/08/2020 23:37:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Apolice]    Script Date: 02/08/2020 23:37:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Apolice](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[ClienteId] [bigint] NOT NULL,
	[CorretorId] [bigint] NOT NULL,
	[Premio] [decimal](16, 2) NOT NULL,
 CONSTRAINT [PK_Apolice] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Cliente]    Script Date: 02/08/2020 23:37:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cliente](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](256) NOT NULL,
	[Cpf] [varchar](11) NOT NULL,
	[DataNascimento] [date] NOT NULL,
	[Sexo] [char](1) NOT NULL,
	[Email] [varchar](256) NOT NULL,
 CONSTRAINT [PK_Cliente] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Cobertura]    Script Date: 02/08/2020 23:37:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cobertura](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](256) NOT NULL,
	[ImportanciaSegurada] [decimal](16, 2) NOT NULL,
	[ApoliceId] [bigint] NOT NULL,
 CONSTRAINT [PK_Cobertura] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Corretor]    Script Date: 02/08/2020 23:37:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Corretor](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](256) NOT NULL,
 CONSTRAINT [PK_Corretor] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Dependente]    Script Date: 02/08/2020 23:37:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Dependente](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](256) NOT NULL,
	[ApoliceId] [bigint] NOT NULL,
 CONSTRAINT [PK_Dependente] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Endereco]    Script Date: 02/08/2020 23:37:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Endereco](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Descricao] [varchar](512) NOT NULL,
	[ClienteId] [bigint] NULL,
 CONSTRAINT [PK_Endereco] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Telefone]    Script Date: 02/08/2020 23:37:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Telefone](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Numero] [varchar](11) NOT NULL,
	[ClienteId] [bigint] NULL,
 CONSTRAINT [PK_Telefone] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [IX_Apolice_ClienteId]    Script Date: 02/08/2020 23:37:59 ******/
CREATE NONCLUSTERED INDEX [IX_Apolice_ClienteId] ON [dbo].[Apolice]
(
	[ClienteId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_Apolice_CorretorId]    Script Date: 02/08/2020 23:37:59 ******/
CREATE NONCLUSTERED INDEX [IX_Apolice_CorretorId] ON [dbo].[Apolice]
(
	[CorretorId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_Cobertura_ApoliceId]    Script Date: 02/08/2020 23:37:59 ******/
CREATE NONCLUSTERED INDEX [IX_Cobertura_ApoliceId] ON [dbo].[Cobertura]
(
	[ApoliceId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_Dependente_ApoliceId]    Script Date: 02/08/2020 23:37:59 ******/
CREATE NONCLUSTERED INDEX [IX_Dependente_ApoliceId] ON [dbo].[Dependente]
(
	[ApoliceId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_Endereco_ClienteId]    Script Date: 02/08/2020 23:37:59 ******/
CREATE NONCLUSTERED INDEX [IX_Endereco_ClienteId] ON [dbo].[Endereco]
(
	[ClienteId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_Telefone_ClienteId]    Script Date: 02/08/2020 23:37:59 ******/
CREATE NONCLUSTERED INDEX [IX_Telefone_ClienteId] ON [dbo].[Telefone]
(
	[ClienteId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Apolice]  WITH CHECK ADD  CONSTRAINT [FK_Apolice_Cliente_ClienteId] FOREIGN KEY([ClienteId])
REFERENCES [dbo].[Cliente] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Apolice] CHECK CONSTRAINT [FK_Apolice_Cliente_ClienteId]
GO
ALTER TABLE [dbo].[Apolice]  WITH CHECK ADD  CONSTRAINT [FK_Apolice_Corretor_CorretorId] FOREIGN KEY([CorretorId])
REFERENCES [dbo].[Corretor] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Apolice] CHECK CONSTRAINT [FK_Apolice_Corretor_CorretorId]
GO
ALTER TABLE [dbo].[Cobertura]  WITH CHECK ADD  CONSTRAINT [FK_Cobertura_Apolice_ApoliceId] FOREIGN KEY([ApoliceId])
REFERENCES [dbo].[Apolice] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Cobertura] CHECK CONSTRAINT [FK_Cobertura_Apolice_ApoliceId]
GO
ALTER TABLE [dbo].[Dependente]  WITH CHECK ADD  CONSTRAINT [FK_Dependente_Apolice_ApoliceId] FOREIGN KEY([ApoliceId])
REFERENCES [dbo].[Apolice] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Dependente] CHECK CONSTRAINT [FK_Dependente_Apolice_ApoliceId]
GO
ALTER TABLE [dbo].[Endereco]  WITH CHECK ADD  CONSTRAINT [FK_Endereco_Cliente_ClienteId] FOREIGN KEY([ClienteId])
REFERENCES [dbo].[Cliente] ([Id])
GO
ALTER TABLE [dbo].[Endereco] CHECK CONSTRAINT [FK_Endereco_Cliente_ClienteId]
GO
ALTER TABLE [dbo].[Telefone]  WITH CHECK ADD  CONSTRAINT [FK_Telefone_Cliente_ClienteId] FOREIGN KEY([ClienteId])
REFERENCES [dbo].[Cliente] ([Id])
GO
ALTER TABLE [dbo].[Telefone] CHECK CONSTRAINT [FK_Telefone_Cliente_ClienteId]
GO
USE [master]
GO
ALTER DATABASE [Apolices] SET  READ_WRITE 
GO
